### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Stalh** [projet-prog-av/issue-tracker#4]
**Describe the bug**
Je test cette fonction

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - 2D lib: [e.g. SDL2] 

**Additional context**

**Comment by Virgile-Dauge** [comment]
Coucou, j'ai bien ton erreur mais je n'ai pas de solutions, bye
