### ISSUE TITLE
[TECH] Utilisation d'algorithmes tiers autorisée ? -> oui, mais

### ISSUE THREAD

**Issue by Esr0g** [projet-prog-av/issue-tracker#6]
J'ai besoin d'une fonction qui permet de savoir si il y'a une collision entre un cercle et un rectancle.  
Je n'ai pas reussi à la coder moi même du coup je suis aller chercher sur internet et j'ai trouvé sur un site des algorithmes bien fait. Ma question est la suivante: ai-je le droit d'utiliser ces algorithmes ? si oui dois-je référencé le site quelque par dans le projet ? (le site en question: http://sdz.tdct.org/sdz/eorie-des-collisions.html)

**Comment by Virgile-Dauge** [comment]
Pas de soucis pour utiliser un algorithme particulier tiré d'internet (s'il est libre de droits). Citer la source est une bonne pratique.
