### ISSUE TITLE
bug world incompris

### ISSUE THREAD

**Issue by Stalh** [projet-prog-av/issue-tracker#7]
**Describe the bug**
Je ne comprends pas pourquoi l'initialisation de mon world pose problème.

**To Reproduce**
1. Go to 'main.c'
2. Enlever les commentaires des lignes de codes du main
3. compiler
4. erreur, il ne comprend pas les flèches ? 

**Expected behavior**
Les fleches sont censés initialiser le vaisseau au position attendu, sa hauteur et sa largeur 

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - 2D lib: [e.g. SDL2]

**Comment by Virgile-Dauge** [comment]
To Reproduce
Steps to reproduce the behavior:

    _Go to 'main.c'_ 
**quelle repo ?**
    Enlever les commentaires des lignes de codes du main
    _compiler_
**Comment ?**
    erreur, il ne comprend pas les flèches ?

J'ai essayé :
```git clone https://github.com/Kalv1/Space-Invader-3003.git 
make```

J'ai obtenu `make: rien à faire pour « all ».`. Pensez à ne pas synchroniser vos fichiers intermédiares (les .o) et vos binaires.

Je n'ai pas trouvé de commentaire à dé commenter dans le main, le git est-il à jour ?

**Comment by Virgile-Dauge** [comment]
Ok j'ai trouvé le main à jour, il est sur la branche dev, pensez à le préciser, je ne peux pas deviner à chaque fois. 
```
 world_t world;

    world->ship.x=600/2;
    world->ship.y=50;
    world->ship.h=30;
    world->ship.w=30;
    world->ship.v=1;
```
Le problème vient de là, vous utilisez des '->' alors que world n'est pas un pointeur.

Prenez le temps de voir les bases de C, internet est riche d'explications à ce sujet. Par exemple :
[https://openclassrooms.com/fr/courses/19980-apprenez-a-programmer-en-c/16119-creez-vos-propres-types-de-variables](https://openclassrooms.com/fr/courses/19980-apprenez-a-programmer-en-c/16119-creez-vos-propres-types-de-variables)
