### ISSUE TITLE
[TECH] Problème d'affichage

### ISSUE THREAD

**Issue by Zixun214** [projet-prog-av/issue-tracker#8]
Your issue may already be reported! Please search on the issue tracker before creating one.
Do not post here if you have not consulted the official documentation beforehand !

**Is your technical question related to a problem? Please describe.**
Il ne peut pas afficher l'écran.

**what does the documentation say ?**
Sur mon terminal :

handuoduodeMacBook-Pro:Space-Invader-3003 zixun$ git checkout dev
Branch 'dev' set up to track remote branch 'dev' from 'origin'.
Switched to a new branch 'dev'
handuoduodeMacBook-Pro:Space-Invader-3003 zixun$ make
make: Nothing to be done for `all'.
handuoduodeMacBook-Pro:Space-Invader-3003 zixun$ ./main
-bash: ./main: cannot execute binary file

**Describe the solution you'd like**
Il va apparaître un écran, même si c'est noir.

**Describe alternatives you've considered**

**Additional context**
J'ai déjà mis les SDL.framwork et SDL_Image.framwork dans mon lib d'ordinateur. Mais il ne marche pas quand même.

**Comment by Virgile-Dauge** [comment]
Essaie de faire un 
```
make clean
```
avant le make.

**Comment by Zixun214** [comment]
c'est bon après je surprime les *.o.
